### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by jwrubel** [knut2/todonotes#1]
The project is missing a license. Log4r is released under LGPLv3 - if you know what license you would like to add, drop a comment here and I'm happy to make a pull request.

**Comment by knut2** [comment]
I just made a small change and added LGPL-3.0  to my gemspec.

Should I add a licence.txt? ( I had no time up to now to look in depth on the licensing details).

**Comment by jwrubel** [comment]
Any of `LICENSE`, `LICENSE.txt`, or `LICENSE.md` added to the root of the project is fine. Either [Licentous](http://licentious.herokuapp.com/) or [AddALicense](http://www.addalicense.com/) can even do it automatically if it's easier.

**Comment by knut2** [comment]
Thanks for the request and the hints how to solve it. 
I released 0.2.2 with the license.
